name: "release"

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  release-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "tenki-macos-latest-mini" # for Arm based macs (M1 and above). You can also use "macos-latest" GitHub Actions runner.
            args: "--target aarch64-apple-darwin"
          - platform: "tenki-macos-latest-mini" # for Intel based macs. You can also use "macos-latest" GitHub Actions runner.
            args: "--target x86_64-apple-darwin"
          - platform: "tenki-standard-autoscale" # You can also use "ubuntu-22.04" GitHub Actions runner.
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: lts/*
          cache: "npm"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          workspaces: "src-tauri -> target"

      - name: Cache and install Tauri system dependencies
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          version: 1.1
        if: matrix.platform == 'ubuntu-22.04'

      - name: install frontend dependencies
        run: npm ci --prefer-offline --no-audit

      - uses: tauri-apps/tauri-action@19b93bb55601e3e373a93cfb6eb4242e45f5af20 # action-v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: agent-one-v__VERSION__
          releaseName: "AgentOne v__VERSION__"
          releaseBody: "See the assets below this release to download and install this version."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
